[12.0] [MIG] l10n_us_form_1099
OCA/l10n-usa pull request #28
Opened 2018-11-16 07:09 UTC by nikul-serpentcs

US Form 1099
============

When companies hire others as contractors, the contractor in question may work for themselves, another company or be the whole other company. This is a huge range, but it can be simplified down to "do I report their payment to the IRS as a 1099?".

This module extends the functionality of a partner and allow you to specify 1099 suppliers.

You will still need to manage payment and IRS reporting separately.

2018-11-16 07:21 UTC, nikul-serpentcs commented
@max3903 @JayVora-SerpentCS Could you please Review it?

2018-11-16 07:33 UTC, bodedra approved these changes

2018-11-16 07:42 UTC, JayVora-SerpentCS requested changes

2018-11-16 07:42 UTC, JayVora-SerpentCS commented on l10n_us_form_1099/models/res_partner.py
> +    is_1099 = fields.Boolean('Is a 1099')
change to : 'Is a 1099?'

2018-11-16 07:44 UTC, nikul-serpentcs commented
@JayVora-SerpentCS Done :+1:

2018-11-16 08:15 UTC, JayVora-SerpentCS approved these changes

2018-11-21 08:30 UTC, merged

2018-11-21 08:31 UTC, JayVora-SerpentCS commented
Thanks @pedrobaeza @max3903

2018-11-21 09:25 UTC, nikul-serpentcs commented
@OCA-git-bot Thanks to reminding 5 days notification :smile: . 

@pedrobaeza Thanks